"""Pydantic models for AI-powered resume enrichment."""

from typing import Any, Literal

from pydantic import BaseModel, Field


class EnrichmentItem(BaseModel):
    """An item identified by AI as needing enrichment."""

    item_id: str  # ID of the experience/project (e.g., "exp_0", "proj_1")
    item_type: str  # "experience" | "project"
    title: str  # Job title or project name
    subtitle: str | None = None  # Company name or project role
    current_description: list[str] = Field(default_factory=list)
    weakness_reason: str  # Why AI flagged this item


class EnrichmentQuestion(BaseModel):
    """A clarifying question generated by AI for an item."""

    question_id: str  # Unique question ID (e.g., "q_0")
    item_id: str  # Which item this question relates to
    question: str  # The question text
    placeholder: str = ""  # Hint for the input field


class AnalysisResponse(BaseModel):
    """Response from AI resume analysis."""

    items_to_enrich: list[EnrichmentItem] = Field(default_factory=list)
    questions: list[EnrichmentQuestion] = Field(default_factory=list)
    analysis_summary: str | None = None  # Optional overall summary


class AnswerInput(BaseModel):
    """User's answer to a clarifying question."""

    question_id: str
    answer: str
    item_id: str | None = None  # When provided, skips redundant re-analysis
    question_text: str | None = None  # Original question for prompt context in fast path


class EnhanceRequest(BaseModel):
    """Request to generate enhanced descriptions from answers."""

    resume_id: str
    answers: list[AnswerInput]


class EnhancedDescription(BaseModel):
    """AI-generated enhanced description for an item."""

    item_id: str
    item_type: str  # "experience" | "project"
    title: str  # For display purposes
    original_description: list[str] = Field(default_factory=list)
    enhanced_description: list[str] = Field(default_factory=list)


class EnhancementPreview(BaseModel):
    """Preview of all enhancements before applying."""

    enhancements: list[EnhancedDescription] = Field(default_factory=list)


class ApplyEnhancementsRequest(BaseModel):
    """Request to apply enhancements to the master resume."""

    enhancements: list[EnhancedDescription]


# ============================================
# AI Regenerate Feature Schemas
# ============================================

RegenerateItemType = Literal["experience", "project", "skills", "summary"]


class RegenerateItemInput(BaseModel):
    """Input for a single item to regenerate."""

    item_id: str  # "exp_0", "proj_1", "skills"
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    current_content: list[str] = Field(default_factory=list)


class RegenerateRequest(BaseModel):
    """Request to regenerate selected resume items."""

    resume_id: str
    items: list[RegenerateItemInput]
    instruction: str = Field(max_length=2000)  # User's feedback/instruction for improvement
    output_language: str = "en"


class RegeneratedItem(BaseModel):
    """Regenerated content for one item."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    original_content: list[str] = Field(default_factory=list)
    new_content: list[str] = Field(default_factory=list)
    new_skill_groups: list[dict[str, Any]] | None = None  # Grouped skills for item_type="skills"
    diff_summary: str = ""  # AI-generated summary of changes


class RegenerateItemError(BaseModel):
    """A non-fatal error for a single item regeneration request."""

    item_id: str
    item_type: RegenerateItemType
    title: str
    subtitle: str | None = None
    message: str


class RegenerateResponse(BaseModel):
    """Response with all regenerated items."""

    regenerated_items: list[RegeneratedItem] = Field(default_factory=list)
    errors: list[RegenerateItemError] = Field(default_factory=list)


# ============================================
# Project Bullet Generation Schemas
# ============================================


class GenerateProjectBulletsRequest(BaseModel):
    """Request to generate resume bullets from a profile project."""

    name: str
    role: str | None = None
    years: str | None = None
    github: str | None = None
    website: str | None = None
    description: list[str] = Field(default_factory=list)
    languages: list[str] = Field(default_factory=list)
    readme: str | None = Field(default=None, max_length=10000)
    prompt: str | None = Field(default=None, max_length=2000)
    output_language: str = "en"


class GenerateProjectBulletsResponse(BaseModel):
    """AI-generated bullet points for a project."""

    bullets: list[str] = Field(default_factory=list)


# ============================================
# Outreach Email Generation Schemas
# ============================================


class GenerateOutreachEmailRequest(BaseModel):
    """Request to generate an outreach email to a company.

    ``purpose`` is one of ``internship``, ``job``, ``cold``, or ``custom``.
    When ``custom``, ``custom_purpose`` carries the user's free-text subject.
    ``resume_id`` optionally selects which resume's profile the email is
    personalized from; when omitted the master resume is used.
    """

    company_name: str
    company_email: str
    industry: str | None = None
    company_size: str | None = None
    company_type: str | None = None
    website: str | None = None
    linkedin_url: str | None = None
    recipient_name: str | None = None
    purpose: str = "internship"
    custom_purpose: str | None = Field(default=None, max_length=2000)
    instruction: str | None = Field(default=None, max_length=2000)
    output_language: str = "en"
    resume_id: str | None = None
    company_research: str | None = Field(default=None, max_length=10000)


class GenerateOutreachEmailResponse(BaseModel):
    """AI-generated outreach email (subject + body)."""

    subject: str = ""
    body: str = ""


# ============================================
# Company Research Schemas
# ============================================


class ResearchCompanyRequest(BaseModel):
    """Request to research a company via web crawling and LinkedIn MCP."""

    company_name: str
    website: str | None = None
    industry: str | None = None
    linkedin_url: str | None = None


class ResearchCompanyResponse(BaseModel):
    """Structured research results for a company."""

    company_name: str
    website_content: str = ""
    linkedin_content: str = ""
    hiring_signals: str = ""
    research_summary: str = ""
    sources: list[str] = Field(default_factory=list)
