"""Sandbox Models — structured workflow execution data types."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class WorkflowStep(BaseModel):
    """A single step in a structured workflow."""

    step_id: str
    tool_name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)
    timeout_ms: int = 15000
    retry_policy: str = "auto"  # auto | never | always


class WorkflowBudget(BaseModel):
    """Execution budget for a workflow."""

    max_steps: int = 10
    max_time_ms: int = 30000
    max_cost_usd: float = 0.05


class Workflow(BaseModel):
    """A structured execution plan generated by the LLM."""

    workflow_id: str
    query: str
    steps: list[WorkflowStep] = Field(default_factory=list)
    budget: WorkflowBudget = Field(default_factory=WorkflowBudget)


class StepResult(BaseModel):
    """Result of executing a single workflow step."""

    step_id: str
    success: bool
    result: Any = None
    error: str | None = None
    latency_ms: float = 0.0


class WorkflowResult(BaseModel):
    """Aggregated result of executing a complete workflow."""

    workflow_id: str
    step_results: list[StepResult] = Field(default_factory=list)
    success: bool = False
    total_time_ms: float = 0.0
